COMPILER = fpc
SOURCES = p.pas analex.pas comentarios.pas \
          io.pas options.pas strings.pas \
			 symtable.pas syntax.pas   

p3_stop: $(SOURCES) 
	$(COMPILER) p.pas

clean:
	rm *.ppu
	rm *.o
	rm p
